### ISSUE TITLE
Simplify startup and reduce need for global dependencies

### ISSUE THREAD

**Issue by joachimprinzbach** [Zuehlke/training-angular2#1]
Hey Stefan

I would recommend to remove the need for having typings and webpack installed globally. 
Use npm scripts to make those commands available to everyone. 

`
    "scripts": {
        "typings": "typings",
                "webpack": "webpack",
        "postinstall": "npm run typings -- install",
                "build": "npm run webpack --config webpack.config.vendor.js"
    }
`

Then typings get installed as a npm postinstall step - simply hit "npm i" and it works. 
To build the app, just run "npm run build".

I can also create a pull request if you want to. Or have a look at another repo: https://github.com/joachimprinzbach/ng2-camp/tree/master/frontend

**Comment by Spontifixus** [comment]
Hi Joachim,

thank you for your input! This would indeed make things simpler.

We did not change the code generated by the project template however, because package management is not a focus in this workshop and we wanted to keep the code of our application as close to the code generated by the template as possible.

Regards,
Markus
